name: mykad
description: Parses Malaysian Identification Card numbers (MyKad)
version: 0.0.1
homepage: https://github.com/pongloongyeat/mykad

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.0
