name: mykad
description: Parses Malaysian Identification Card numbers (MyKad)
version: 1.0.0
homepage: https://github.com/pongloongyeat/mykad

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0
